In [64]:
import pandas as pd
market= pd.read_csv("market.csv")
properties= pd.read_csv("properties.csv")
pd.set_option('display.max_columns',None)

In [3]:
market.head(2)

,City,Year,Avg_Home_Price,Avg_Rent_Price,Housing_Demand_Index,Unemployment_Rate,Interest_Rate,New_Construction_Count,Investor_Activity_Score,Income_Bracket,Affordability_Avg_Home_Price,Affordability_Median_Household_Income,Affordability_Price_to_Income_Ratio,Affordability_Change_YoY
0,New York,2019,553835.022695,4680.864035,96.033028,4.902321,3.5,414,2.160855,$50k-$75k,789397.031044,62000,5.601860,-0.603177
1,New York,2019,553835.022695,4680.864035,96.033028,4.902321,3.5,414,2.160855,$75k-$100k,762631.647135,88000,6.112348,-0.988917

In [4]:
properties.head(2)

,Property_ID,Type,City,Size_SqFt,Bedrooms,Bathrooms,Year_Built,Listing_Price,Rental_Price,Neighborhood,Status
0,1,Condo,Chicago,4934,4,2,1989,1153430.619,4719.426366,The Loop,Rented
1,2,Townhouse,Los Angeles,3960,5,2,2012,1101016.067,4256.943395,Beverly Hills,Available

In [5]:
market.shape

(120, 14)

In [6]:
properties.shape

(20000, 11)

In [7]:
market.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 14 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   City                                   120 non-null    object
 1   Year                                   120 non-null    int64
 2   Avg_Home_Price                         120 non-null    float64
 3   Avg_Rent_Price                         120 non-null    float64
 4   Housing_Demand_Index                   120 non-null    float64
 5   Unemployment_Rate                      120 non-null    float64
 6   Interest_Rate                          120 non-null    float64
 7   New_Construction_Count                 120 non-null    int64
 8   Investor_Activity_Score                120 non-null    float64
 9   Income_Bracket                         120 non-null    object
 10  Affordability_Avg_Home_Price           120 non-null    float64
 11  Affordability_Median_Household_Income  120 non-null    int64
 12  Affordability_Price_to_Income_Ratio    120 non-null    float64
 13  Affordability_Change_YoY               120 non-null    float64
dtypes: float64(9), int64(3), object(2)
memory usage: 13.3+ KB

In [8]:
properties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Property_ID    20000 non-null  int64
 1   Type           20000 non-null  object
 2   City           20000 non-null  object
 3   Size_SqFt      20000 non-null  int64
 4   Bedrooms       20000 non-null  int64
 5   Bathrooms      20000 non-null  int64
 6   Year_Built     20000 non-null  int64
 7   Listing_Price  20000 non-null  float64
 8   Rental_Price   20000 non-null  float64
 9   Neighborhood   20000 non-null  object
 10  Status         20000 non-null  object
dtypes: float64(2), int64(5), object(4)
memory usage: 1.7+ MB

In [9]:
market.describe()

,Year,Avg_Home_Price,Avg_Rent_Price,Housing_Demand_Index,Unemployment_Rate,Interest_Rate,New_Construction_Count,Investor_Activity_Score,Affordability_Avg_Home_Price,Affordability_Median_Household_Income,Affordability_Price_to_Income_Ratio,Affordability_Change_YoY
count,120.000000,1.200000e+02,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,2021.000000,6.602258e+05,3072.054397,122.603459,8.252163,4.500000,542.733333,4.336422,728646.696973,112500.000000,5.963860,-1.741557
std,1.420143,2.934202e+05,1653.552520,42.599248,2.308142,0.710072,296.080495,2.521152,141887.229244,44238.657569,0.553105,0.743537
min,2019.000000,2.109368e+05,878.042313,54.350861,3.425338,3.500000,50.000000,0.176708,427105.437972,62000.000000,5.057077,-2.921965
25%,2020.000000,4.207401e+05,1554.643701,87.306803,6.925976,4.000000,248.000000,2.904103,620038.166886,81500.000000,5.562250,-2.336556
50%,2021.000000,6.546254e+05,2443.548294,117.222267,8.205062,4.500000,597.500000,3.893355,770166.579735,104000.000000,5.936824,-1.716636
75%,2022.000000,8.844508e+05,4680.864035,158.643285,10.102687,5.000000,843.000000,6.356184,823617.300371,135000.000000,6.353076,-0.982364
max,2023.000000,1.197710e+06,5946.996102,193.954217,11.771441,5.500000,995.000000,8.813020,899820.144745,180000.000000,6.811359,-0.603177

In [10]:
properties.describe()

,Property_ID,Size_SqFt,Bedrooms,Bathrooms,Year_Built,Listing_Price,Rental_Price
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000e+04,20000.000000
mean,10000.500000,2759.178300,3.001750,1.996200,1985.950550,1.045990e+06,4228.024226
std,5773.647028,1287.689078,1.415891,0.816835,21.067242,5.424043e+05,2168.353927
min,1.000000,500.000000,1.000000,1.000000,1950.000000,1.000558e+05,500.206474
25%,5000.750000,1669.000000,2.000000,1.000000,1968.000000,5.758856e+05,2340.959264
50%,10000.500000,2759.000000,3.000000,2.000000,1986.000000,1.052078e+06,4214.406773
75%,15000.250000,3867.000000,4.000000,3.000000,2004.000000,1.508498e+06,6102.653908
max,20000.000000,4999.000000,5.000000,3.000000,2022.000000,1.999985e+06,7999.409770

In [11]:
#Invalid Listing Price check

invalid_price = properties[properties["Listing_Price"]<=0]
invalid_price

Empty DataFrame
Columns: [Property_ID, Type, City, Size_SqFt, Bedrooms, Bathrooms, Year_Built, Listing_Price, Rental_Price, Neighborhood, Status]
Index: []

No invalid listing prices found. Pricing data is clean and reliable.

In [14]:
#Listing Price Range Analysis

print("Minimum Price: ", properties["Listing_Price"].min())
print("Maximum Price: ", properties["Listing_Price"].max())
print("Average Price: ", properties["Listing_Price"].mean())

Minimum Price:  100055.7649
Maximum Price:  1999984.88
Average Price:  1045989.6416908726

In [16]:
#Property Size validation

print("Minimum Size :", properties["Size_SqFt"].min())

print("Maximum Size :", properties["Size_SqFt"].max())

print("Average Size :", round(properties["Size_SqFt"].mean(),2))

Minimum Size : 500
Maximum Size : 4999
Average Size : 2759.18

In [18]:
# How do property prices vary by property type?

avg_price = properties.groupby("Type")["Listing_Price"].mean().round(2).sort_values(ascending=False).reset_index(name="Avg_Listing_Price")
avg_price

        Type  Avg_Listing_Price
0  Townhouse         1057516.95
1      Other         1054058.05
2  Apartment         1045960.18
3      Condo         1045217.97
4      House         1034232.79

Townhouses recorded the highest average listing price, indicating they represent the premium segment of the housing market.
Houses had the lowest average listing price, making them comparatively more affordable than other property types.
Apartments and Condos showed very similar average prices, suggesting consistent pricing across these categories.
The difference in average prices across property types is relatively small, indicating a balanced pricing structure in the dataset.
Overall, property type has a moderate influence on listing prices, with Townhouses commanding a slight price premium.

In [15]:
# Which Property Types Are Most Frequently Listed?

listing_count= properties["Type"].value_counts().sort_values(ascending=False)
listing_count

Type
Apartment    4953
Townhouse    4845
House        4837
Condo        4765
Other         600
Name: count, dtype: int64

In [11]:
# Which property types are most frequently listed in each city?

properties.groupby(["Type","City"]).size().reset_index(name="Total_Listings").sort_values(by="Total_Listings",ascending=False)

         Type           City  Total_Listings
5   Apartment        Seattle             874
6       Condo        Chicago             837
0   Apartment        Chicago             836
2   Apartment          Miami             836
25  Townhouse    Los Angeles             835
26  Townhouse          Miami             830
24  Townhouse        Chicago             821
14      House          Miami             821
12      House        Chicago             820
16      House  San Francisco             820
1   Apartment    Los Angeles             819
15      House       New York             814
8       Condo          Miami             814
29  Townhouse        Seattle             809
3   Apartment       New York             809
7       Condo    Los Angeles             807
9       Condo       New York             807
17      House        Seattle             790
28  Townhouse  San Francisco             782
4   Apartment  San Francisco             779
13      House    Los Angeles             772
27  Townhouse       New York             768
10      Condo  San Francisco             754
11      Condo        Seattle             746
21      Other       New York             118
22      Other  San Francisco             112
19      Other    Los Angeles             105
20      Other          Miami             103
23      Other        Seattle              83
18      Other        Chicago              79

In [21]:
# Which Cities Have the Highest Average Home Prices?

avg_home_price = market.groupby("City")["Avg_Home_Price"].mean().sort_values(ascending=False).round(2).reset_index(name="Avg_Home_Price")
avg_home_price

            City  Avg_Home_Price
0  San Francisco       830678.07
1          Miami       824967.27
2        Chicago       721928.03
3        Seattle       566786.64
4       New York       530707.34
5    Los Angeles       486287.20

In [22]:
 # How Have Home Prices Changed Over Time?

# Step 1: Calculate average home price for each city and year

avg_price_year = (
    market.groupby(["City", "Year"])["Avg_Home_Price"]
    .mean()
    .reset_index()
)

# Step 2: Get previous year's average home price for each city

avg_price_year["Previous_Price"] = (
    avg_price_year.groupby("City")["Avg_Home_Price"]
    .shift(1)
)

# Step 3: Calculate Year-over-Year (YoY) Growth Percentage

avg_price_year["YoY_Growth (%)"] = (
    (avg_price_year["Avg_Home_Price"] - avg_price_year["Previous_Price"])
    / avg_price_year["Previous_Price"]
) * 100

# Round the growth values

avg_price_year["YoY_Growth (%)"] = avg_price_year["YoY_Growth (%)"].round(2)

# final result

avg_price_year

             City  Year  Avg_Home_Price  Previous_Price  YoY_Growth (%)
0         Chicago  2019    1.073395e+06             NaN             NaN
1         Chicago  2020    8.965788e+05    1.073395e+06          -16.47
2         Chicago  2021    5.138254e+05    8.965788e+05          -42.69
3         Chicago  2022    7.337326e+05    5.138254e+05           42.80
4         Chicago  2023    3.921083e+05    7.337326e+05          -46.56
5     Los Angeles  2019    6.424242e+05             NaN             NaN
6     Los Angeles  2020    2.109368e+05    6.424242e+05          -67.17
7     Los Angeles  2021    2.146998e+05    2.109368e+05            1.78
8     Los Angeles  2022    1.138868e+06    2.146998e+05          430.45
9     Los Angeles  2023    2.245067e+05    1.138868e+06          -80.29
10          Miami  2019    1.197710e+06             NaN             NaN
11          Miami  2020    7.544765e+05    1.197710e+06          -37.01
12          Miami  2021    4.832722e+05    7.544765e+05          -35.95
13          Miami  2022    8.049273e+05    4.832722e+05           66.56
14          Miami  2023    8.844508e+05    8.049273e+05            9.88
15       New York  2019    5.538350e+05             NaN             NaN
16       New York  2020    7.039825e+05    5.538350e+05           27.11
17       New York  2021    3.259601e+05    7.039825e+05          -53.70
18       New York  2022    4.694392e+05    3.259601e+05           44.02
19       New York  2023    6.003199e+05    4.694392e+05           27.88
20  San Francisco  2019    4.207401e+05             NaN             NaN
21  San Francisco  2020    6.668266e+05    4.207401e+05           58.49
22  San Francisco  2021    1.097071e+06    6.668266e+05           64.52
23  San Francisco  2022    1.094284e+06    1.097071e+06           -0.25
24  San Francisco  2023    8.744687e+05    1.094284e+06          -20.09
25        Seattle  2019    8.289492e+05             NaN             NaN
26        Seattle  2020    4.540593e+05    8.289492e+05          -45.22
27        Seattle  2021    3.142813e+05    4.540593e+05          -30.78
28        Seattle  2022    9.136761e+05    3.142813e+05          190.72
29        Seattle  2023    3.229674e+05    9.136761e+05          -64.65

In [39]:
# Which City Recorded the Highest Property Values Each Year?

highest_price = market.sort_values(by="Avg_Home_Price",ascending=False).groupby("Year")[["City","Avg_Home_Price"]].first().reset_index()
highest_price["Avg_Home_Price"] = highest_price["Avg_Home_Price"].round(2)
highest_price

   Year           City  Avg_Home_Price
0  2019          Miami      1197709.64
1  2020        Chicago       896578.76
2  2021  San Francisco      1097071.31
3  2022    Los Angeles      1138868.50
4  2023          Miami       884450.75

In [40]:
# Which City Recorded the Lowest Property Values Each Year?
lowest_price = market.sort_values(by="Avg_Home_Price").groupby("Year")[["City","Avg_Home_Price"]].first().reset_index()
lowest_price["Avg_Home_Price"]= lowest_price["Avg_Home_Price"].round(2)
lowest_price

   Year           City  Avg_Home_Price
0  2019  San Francisco       420740.15
1  2020    Los Angeles       210936.81
2  2021    Los Angeles       214699.77
3  2022       New York       469439.21
4  2023    Los Angeles       224506.74

In [50]:
# Which Cities Exhibit the Strongest Housing Demand, and What Are the Typical Home and Rental Prices?

housing_demand = (market.groupby("City").agg({"Housing_Demand_Index":"mean", "Avg_Home_Price":"mean","Avg_Rent_Price":"mean"})
                    .round(2)
                    .sort_values(by="Housing_Demand_Index",ascending=False)
                    .reset_index())
housing_demand

            City  Housing_Demand_Index  Avg_Home_Price  Avg_Rent_Price
0  San Francisco                162.35       830678.07         3934.04
1        Chicago                129.52       721928.03         2680.01
2        Seattle                122.11       566786.64         3638.35
3          Miami                117.80       824967.27         2659.77
4    Los Angeles                105.20       486287.20         2919.57
5       New York                 98.63       530707.34         2600.59

In [56]:
# Which Cities Attract the Highest Investor Activity?

investor_activity = (market.groupby("City")["Investor_Activity_Score"].mean().round(2)
    .sort_values(ascending=False).reset_index(name="Avg_Investor_Activity"))

investor_activity["Investor_Rank"] = investor_activity["Avg_Investor_Activity"].rank(method="dense",ascending=False)
investor_activity

            City  Avg_Investor_Activity  Investor_Rank
0    Los Angeles                   5.13            1.0
1        Chicago                   5.01            2.0
2          Miami                   4.57            3.0
3        Seattle                   4.54            4.0
4  San Francisco                   3.64            5.0
5       New York                   3.12            6.0

In [57]:
# Which Income Groups Face the Greatest Housing Affordability Challenges?

affordability = (
    market.groupby("Income_Bracket")["Affordability_Price_to_Income_Ratio"]
    .mean()
    .round(2)
    .reset_index(name="Price_to_Income_Ratio")
)

def affordability_status(ratio):
    if ratio >= 6:
        return "Severely Unaffordable"
    elif ratio >= 5:
        return "Moderately Unaffordable"
    elif ratio >= 4:
        return "Slightly Unaffordable"
    else:
        return "Affordable"

affordability["Affordability_Stress"] = (
    affordability["Price_to_Income_Ratio"]
    .apply(affordability_status)
)

affordability

  Income_Bracket  Price_to_Income_Ratio     Affordability_Stress
0    $100k-$150k                   6.48    Severely Unaffordable
1         $150k+                   5.87  Moderately Unaffordable
2      $50k-$75k                   5.54  Moderately Unaffordable
3     $75k-$100k                   5.97  Moderately Unaffordable

In [69]:
#Q1. Which Years Recorded the Highest Number of New Property Developments?

new_construction = market.groupby("Year")["New_Construction_Count"].sum().sort_values(ascending=False).reset_index(name="New_Properties_built")
new_construction

   Year  New_Properties_built
0  2020                 21844
1  2019                 15516
2  2021                 10016
3  2023                  8980
4  2022                  8772

In [70]:
# Which Cities Experienced the Highest Level of New Construction Activity?
new_construction_city = (
    market.groupby("City")["New_Construction_Count"]
    .sum()
    .reset_index(name="New_Properties_Built")
    .sort_values(by="New_Properties_Built", ascending=False)
)

new_construction_city

            City  New_Properties_Built
1    Los Angeles                 13696
5        Seattle                 12604
0        Chicago                 10736
4  San Francisco                 10156
2          Miami                 10092
3       New York                  7844

In [71]:
# How Does New Construction Influence Home Prices?
construction_price = (
    market.groupby("Year")
    .agg({
        "New_Construction_Count": "sum",
        "Avg_Home_Price": "mean"
    })
    .round(2)
    .reset_index()
)

construction_price

   Year  New_Construction_Count  Avg_Home_Price
0  2019                   15516       786175.55
1  2020                   21844       614476.74
2  2021                   10016       491518.33
3  2022                    8772       859154.55
4  2023                    8980       549803.62

In [78]:
# How Do Interest Rates Impact Average Home Prices?

interest_rate = market.groupby("Interest_Rate")["Avg_Home_Price"].mean().round(2).reset_index(name="Average_Home_Price")
interest_rate["Previous_Price"]= interest_rate["Average_Home_Price"].shift(1)
interest_rate["Percent_change"] = (interest_rate["Average_Home_Price"]-interest_rate["Previous_Price"])/interest_rate["Previous_Price"]*100
interest_rate["Percent_change"]=interest_rate["Percent_change"].round(2)
interest_rate

   Interest_Rate  Average_Home_Price  Previous_Price  Percent_change
0            3.5           786175.55             NaN             NaN
1            4.0           614476.74       786175.55          -21.84
2            4.5           491518.33       614476.74          -20.01
3            5.0           859154.55       491518.33           74.80
4            5.5           549803.62       859154.55          -36.01